# Generated by Django 4.0.6 on 2022-09-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipo', models.CharField(max_length=100, verbose_name='Equipo')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('jira', models.CharField(max_length=30, verbose_name='Jira')),
                ('devops', models.CharField(max_length=50, verbose_name='Devops')),
                ('refDev', models.CharField(max_length=100, verbose_name='Referente Dev')),
                ('refQA', models.CharField(max_length=100, verbose_name='Referente QA')),
                ('nvlCode', models.IntegerField(max_length=30, verbose_name='Nivel Calidad Codigo')),
                ('nvlAuto', models.IntegerField(max_length=30, verbose_name='Nivel Regression QA')),
                ('comentario', models.CharField(max_length=500, verbose_name='Comentario')),
            ],
        ),
    ]
